language: java
jdk:
    -openjdk8

services:
  - xvfb

before_install:
  - sudo apt update
  - sudo apt install openjfx
  - chmod +x ./gradlew
  - export DISPLAY=:99.0

install: true

addons:
    apt:
      packages:
        ant
    sonarcloud:
    organization: ferra-rally
    token:
        secure: 7c76f8ff222da584e74f9209d5a955ffb959c5a2
script:
    - ant build
    - sonar-scanner
